---
# Configuration tasks

- block:
    - include_tasks: "{{ configure_playbook }}"
      vars:
        configure_playbook: >-
          {{ role_path
             + "/tasks/configure/"
             + ansible_facts.os_family | lower
             + ".yml" }}

    - include_tasks: "{{ role_path }}/tasks/configure/common.yml"
  tags:
    - role::docker_engine
    - role::docker_engine::configure
